### ISSUE TITLE
students struggled to understand task

### ISSUE THREAD

**Issue by siandav** [ironhack-edu/data_2.05_activities#3]
the tables are already linked but the task says to draw the structure out with links... confused. 

also the tables are named differently in the diagram from the actual database which makes it confusing. 

on first read i thought this one would be fine, but though they do understand the concept, they really didnt like the activity. 

can we give them just the tables, and ask them to draw the links, the cardinality, and label the keys - maybe give them an editable file ? 
or can this be done in class, interactively in some way

maybe theres an online version of the same activity? 

@sandrabosk

**Comment by ironhack-edu** [comment]
@haggarw3 Have we solved this issue with the updates in the activities?

**Comment by haggarw3** [comment]
I have replaced the question with image of another database, Sakila DB. The students just need to figure out the primary keys and foreign keys for each table in this activity.

**Comment by haggarw3** [comment]
@siandav Could you please mention the specific activity number so that it's easier to find it. Thanks :D
